# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Airan < Formula
  desc "The env for AI coding agents — a shebang dispatcher for agent files"
  homepage "https://github.com/kfet/airan"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/airan/releases/download/v0.1.1/airan-darwin-amd64"
      sha256 "f40eae108692091c7ee9b7c08a684a0c94031ddc1c3dd3586f7976c4466012e9"

      def install
        bin.install Dir["airan-*"].first => "airan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/airan/releases/download/v0.1.1/airan-darwin-arm64"
      sha256 "016a0812261a09f34d6ee3ad12aea3657200fc6fddbf7d67c334c276d70f9ed9"

      def install
        bin.install Dir["airan-*"].first => "airan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/airan/releases/download/v0.1.1/airan-linux-amd64"
      sha256 "c922f1b54f9f7edd77092d05be7102cadabafae34e14b2873c78b05fbc600b20"
      def install
        bin.install Dir["airan-*"].first => "airan"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/airan/releases/download/v0.1.1/airan-linux-arm"
      sha256 "83b436df8d4dacdbe61674c6824865b0be37678f67a406f1902f1b635ed6225a"
      def install
        bin.install Dir["airan-*"].first => "airan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/airan/releases/download/v0.1.1/airan-linux-arm64"
      sha256 "ca83c0e79b98b206094d2550fd93788d9dc798db45e72633266b09cc3fdf04a7"
      def install
        bin.install Dir["airan-*"].first => "airan"
      end
    end
  end

  test do
    system "#{bin}/airan", "backends"
  end
end
