# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Airan < Formula
  desc "The env for AI coding agents — a shebang dispatcher for agent files"
  homepage "https://github.com/kfet/airan"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/airan/releases/download/v0.1.4/airan-darwin-amd64"
      sha256 "4dc7d01c1290f0d2f3368564cc1c7dea2426556c6a69d57f63a1f8330ccf6a9c"

      define_method(:install) do
        bin.install Dir["airan-*"].first => "airan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/airan/releases/download/v0.1.4/airan-darwin-arm64"
      sha256 "84fcd736b80f3c2caca0872c5b05b5cb87c881e8fa1711b11d657efecedc3100"

      define_method(:install) do
        bin.install Dir["airan-*"].first => "airan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/airan/releases/download/v0.1.4/airan-linux-amd64"
      sha256 "d1d6354107cb69ce7365a1696ae407966b54cbdf61626cd6a440bf7c154f82d1"
      define_method(:install) do
        bin.install Dir["airan-*"].first => "airan"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/airan/releases/download/v0.1.4/airan-linux-arm"
      sha256 "4caf04c105a7bd836f338b60a98dfff57caef57df95e0497e114cbd7b9bacbe7"
      define_method(:install) do
        bin.install Dir["airan-*"].first => "airan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/airan/releases/download/v0.1.4/airan-linux-arm64"
      sha256 "614f707a605ec234ccfbbaf609adde61331ce24886408fab2eebf526769976c0"
      define_method(:install) do
        bin.install Dir["airan-*"].first => "airan"
      end
    end
  end

  test do
    system "#{bin}/airan", "version"
  end
end
