# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fir < Formula
  desc "Fast, portable AI coding agent"
  homepage "https://github.com/kfet/fir"
  version "1.10.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.10.2/fir-darwin-amd64"
      sha256 "be349de6fdebc8b99d090958fe8cb047a6402461e554987e439e0afbae56c79d"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.10.2/fir-darwin-arm64"
      sha256 "d82c520ddcf6fdcc8b67451c146905fb1c2840d0c4cb8820a72837aa71d1bb1a"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.10.2/fir-linux-amd64"
      sha256 "cfa7373da13ca7686a953f2e6a9e3051826af66703cf933da9dcc3e75c9afc4b"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.10.2/fir-linux-armv6"
      sha256 "891323448661fdcb866c204b466143ef868859c2d117e2837bd6d2ebb72e12cf"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.10.2/fir-linux-arm64"
      sha256 "6cd6c10bf55727604e4c9a1c7039d7a7eb1680fb685ab6abe48c0f5a7a010df1"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
