# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fir < Formula
  desc "Fast, portable AI coding agent"
  homepage "https://github.com/kfet/fir"
  version "0.65.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.65.4/fir-darwin-amd64"
      sha256 "7bc5d0bc00e3bcc1a0e89e9545f6d5ec98540e2933dc6a1116bdf09b35771323"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.65.4/fir-darwin-arm64"
      sha256 "0c57da80ff1b34cee9b737146ab9e46c4a0ec9a1e99eb436bebdecb7624d625f"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.65.4/fir-linux-amd64"
      sha256 "1e62f1ca0ddf90f22720470ffa6c5e37a4314ea1db2962187133d3afca033394"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.65.4/fir-linux-armv6"
      sha256 "df57106917db2ccbc946a997d3beff601fdc2718df9811f2b66ef0492cb7c386"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.65.4/fir-linux-arm64"
      sha256 "152eab5da2304c0e056ede8590d92c69dcbe497c110acbff267d4fdb2b17b54d"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
