# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT19 < Formula
  desc "Fast, portable AI coding agent (pinned 1.9)"
  homepage "https://github.com/kfet/fir"
  version "1.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.9.1/fir-darwin-amd64"
      sha256 "a4ab2497ad2e154a42d0b6126d1b531411ac596dfbcfbc4438d6f20ba3a7e0f2"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.9.1/fir-darwin-arm64"
      sha256 "fb8f30ff2cf54946616aecd385705108096a53c3b72bafea44d39ebd558ae084"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.9.1/fir-linux-amd64"
      sha256 "b94e7093e335bee2f0c62480158fca517c78d82dedb2c146ab88006aba14009f"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.9.1/fir-linux-armv6"
      sha256 "b6106fd56fb1227c4637baa9fbb5b25d20d2f9c36de503e8c307e2a3c469274f"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.9.1/fir-linux-arm64"
      sha256 "f26c98f1af655094920eedf6e5b35d3a1ab2763a33e901fa02c533cc53e3ac32"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.9). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.9

      To go back to the rolling latest:
        brew unlink fir@1.9
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
