# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT078 < Formula
  desc "Fast, portable AI coding agent (pinned 0.78)"
  homepage "https://github.com/kfet/fir"
  version "0.78.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.78.0/fir-darwin-amd64"
      sha256 "74355b9adf8e4473b1a473721c6fa3c9a46b1bce532601b09f82d34bf163ad8d"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.78.0/fir-darwin-arm64"
      sha256 "63f2d1e9ff63391bfff1d93d22bf5dec56d06e2d6fc76de2c7144b184711eca5"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.78.0/fir-linux-amd64"
      sha256 "426dbb28ab76a1e3f1049bbe7feed2d4e7c83eac390a4a3076ede669c37de589"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.78.0/fir-linux-armv6"
      sha256 "a03de9466ed43f7478e6b612fedf3880e19ac551305f261aca83bc6bb53aa50d"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.78.0/fir-linux-arm64"
      sha256 "e8112018b090653c39fb5634c5b542f7c324519d821ff878bf98a5e454738830"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.78). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.78

      To go back to the rolling latest:
        brew unlink fir@0.78
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
