# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT074 < Formula
  desc "Fast, portable AI coding agent (pinned 0.74)"
  homepage "https://github.com/kfet/fir"
  version "0.74.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.74.3/fir-darwin-amd64"
      sha256 "f424bcb3d764f55ca446772fb6a07c5b04ea235bb2f1c1cd0339cfba5b01325a"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.74.3/fir-darwin-arm64"
      sha256 "43c860e5963ea0c44ce3713a98cec0534ec3b105018eb6370a57b20313b1e087"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.74.3/fir-linux-amd64"
      sha256 "b3504b5297bb4a30c843e4605bd4c819a928ebe3c093304d356a349aec44d2c8"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.74.3/fir-linux-armv6"
      sha256 "2019bbccfb566098afd4537e44be35a94a4471758ac51d4e89b855b295740093"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.74.3/fir-linux-arm64"
      sha256 "3a04c1d61d40d7a183a156cc08228c4c464684b1a9fe1be9fc9de127097f0861"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.74). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.74

      To go back to the rolling latest:
        brew unlink fir@0.74
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
