# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT050 < Formula
  desc "Fast, portable AI coding agent (pinned 0.50)"
  homepage "https://github.com/kfet/fir"
  version "0.50.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.50.0/fir-darwin-amd64"
      sha256 "505954e215aad1b18895a5b72c178ecb85de8234959400c19c46eaf75f28e2cf"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.50.0/fir-darwin-arm64"
      sha256 "b1dcb9467ece1e2b737bda2f1edb46fc0e31aad550d46141f0c2ec1fc7685db5"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.50.0/fir-linux-amd64"
      sha256 "c4d9ffb64fc5bd235f6eb15e78304fe09a99c9b20fd4567278afe09ac67abd07"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.50.0/fir-linux-armv6"
      sha256 "8d4ec7ce8ad7f16cb3d826635a41fce84ccfbc074be72911b7e257f8706ab07e"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.50.0/fir-linux-arm64"
      sha256 "20de2b5464ae9896719fc25d6c0c6f56263a7606fe62128a3552630d15189cca"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.50). It ships
      its own bin/fir, which collides with the rolling kfet/fir/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.50

      To go back to the rolling latest:
        brew unlink fir@0.50
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
