# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT119 < Formula
  desc "Fast, portable AI coding agent (pinned 1.19)"
  homepage "https://github.com/kfet/fir"
  version "1.19.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.19.0/fir-darwin-amd64"
      sha256 "f1e98a41c03ce64b253a587dc613a2fcf8240b48184530b77d5db3ea1da5abda"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.19.0/fir-darwin-arm64"
      sha256 "96c13dd318a57b43a0ae52ba3bfeefd15df2460d487f2034708656bbb8f2f4db"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.19.0/fir-linux-amd64"
      sha256 "24ec251f9cb5359ab4ab4912441e8dd4adda11d85641e040de1d2d8c7bc528ca"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.19.0/fir-linux-armv6"
      sha256 "f5a0635c2e08139c641ae818980635d614aa5fd3d127e88b8a51c3da29914a5d"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.19.0/fir-linux-arm64"
      sha256 "44290b66196dfcc58c112493d990d7bd338443e416d7a5a61886e2d6e23376cb"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.19). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.19

      To go back to the rolling latest:
        brew unlink fir@1.19
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
