# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT123 < Formula
  desc "Fast, portable AI coding agent (pinned 1.23)"
  homepage "https://github.com/kfet/fir"
  version "1.23.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.23.1/fir-darwin-amd64"
      sha256 "e7842439aa102f27501a006fe8e37655b08e969d0cfa789dccf4bbdd2c6f0c25"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.23.1/fir-darwin-arm64"
      sha256 "1e6022441ce0187b5e649e7ab5a44efaa7c94798207b86050f1e33c717487231"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.23.1/fir-linux-amd64"
      sha256 "e044ae1f4cd20d20168e0bfda2d891624a80d7f65609785615918942bc7a78cd"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.23.1/fir-linux-armv6"
      sha256 "48458aabd283b9d0036ae200edfc35a7227d62a3e703db008392190789df845f"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.23.1/fir-linux-arm64"
      sha256 "0b90badde3cdd6187703b630e03aa3dae41af8f9b82001963f63b412c34f175a"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.23). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.23

      To go back to the rolling latest:
        brew unlink fir@1.23
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
