# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT096 < Formula
  desc "Fast, portable AI coding agent (pinned 0.96)"
  homepage "https://github.com/kfet/fir"
  version "0.96.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.96.0/fir-darwin-amd64"
      sha256 "5de3a932fa95a81483068bb0241e15d9aa8b73942f1929f25a3bee75b03390c5"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.96.0/fir-darwin-arm64"
      sha256 "75f314a692cd4a06e06f9de5f25b04085ba0bf05289de76086e9c58258778449"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.96.0/fir-linux-amd64"
      sha256 "f6f0338d4b84ba334435b0f325b5f0c528d54cf869783cbfd862fcd32747435e"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.96.0/fir-linux-armv6"
      sha256 "1ccc0105e49957a0cfdbf3bf87c13b73cfffbee9323b87392430f957517ad8f3"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.96.0/fir-linux-arm64"
      sha256 "767c535bfbd13c713c4fd77052c1ed412e33c9f9406645915543d03a1118df89"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.96). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.96

      To go back to the rolling latest:
        brew unlink fir@0.96
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
