# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT114 < Formula
  desc "Fast, portable AI coding agent (pinned 1.14)"
  homepage "https://github.com/kfet/fir"
  version "1.14.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.14.0/fir-darwin-amd64"
      sha256 "811a737619730035c2f987a0a95e610f4ebf534284ac35dcec702dae9fceed00"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.14.0/fir-darwin-arm64"
      sha256 "59bb48ce9c5fa2467ad0b11d31f23c509a1bb7ec5b7f25800ceb9f3bc5a7404d"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.14.0/fir-linux-amd64"
      sha256 "182875f116a47a67b65b689f7f57543117d9335a556658914363a152d60be245"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.14.0/fir-linux-armv6"
      sha256 "d44c0d57a849e1c7d62ab2927c166eb071c554184aed975cbec08bc6dacbcf76"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.14.0/fir-linux-arm64"
      sha256 "ada1152f56ee82b2dca86fa80d2d1b217e62ac9af9db678786e2407cae96298b"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.14). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.14

      To go back to the rolling latest:
        brew unlink fir@1.14
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
