# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT125 < Formula
  desc "Fast, portable AI coding agent (pinned 1.25)"
  homepage "https://github.com/kfet/fir"
  version "1.25.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.25.0/fir-darwin-amd64"
      sha256 "311da8258970aa06a795d8d5f32caa51623c5cbed438250cd2624afbf8a9e658"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.25.0/fir-darwin-arm64"
      sha256 "2bd2bba5747d746bac4349139f09f0bd68eb738948413799fa1c4bde05fda231"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.25.0/fir-linux-amd64"
      sha256 "f4091670c0b7714c73d95fce6e5d5f8c3217410c58af0d40ee7ae35972a09729"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.25.0/fir-linux-armv6"
      sha256 "f5b9f3e1a03340676ca1e32ff11a17eb978adb09a3b19f572ed2415c99e2797b"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.25.0/fir-linux-arm64"
      sha256 "5dc95792dee0980cfb23e3c473367bcac94b8e5e1d566f7259fb51aa6cc12fb9"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.25). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.25

      To go back to the rolling latest:
        brew unlink fir@1.25
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
