# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT074 < Formula
  desc "Fast, portable AI coding agent (pinned 0.74)"
  homepage "https://github.com/kfet/fir"
  version "0.74.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.74.0/fir-darwin-amd64"
      sha256 "2d1399e9b60c15057fa42be56f475c80416485e5714a6a6e80d398a5851ebabf"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.74.0/fir-darwin-arm64"
      sha256 "b5cd3c46132b72d6f184ce53016506b24f989d5277048accb8bd024505141c7b"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.74.0/fir-linux-amd64"
      sha256 "43e65f4410656a5b8e652066d71485baeca3db90cf10bd5c939a19e03f2ac2c2"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.74.0/fir-linux-armv6"
      sha256 "307c17d36c82b99d86e1eb1ac1a69ee45f40e4c2db54035fd52d6d7c7e3ef0b4"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.74.0/fir-linux-arm64"
      sha256 "8d17bb58eae9c022f201b50cd00207347faf8d792636ac5f419444bfe165cac0"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.74). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.74

      To go back to the rolling latest:
        brew unlink fir@0.74
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
