# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT118 < Formula
  desc "Fast, portable AI coding agent (pinned 1.18)"
  homepage "https://github.com/kfet/fir"
  version "1.18.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.18.3/fir-darwin-amd64"
      sha256 "508ab45627137037081c6656f2e275ae7e6c61759e3c35434f869f7a1880b3b6"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.18.3/fir-darwin-arm64"
      sha256 "23217bf096842b36d96293d83c841990435511b2c63ea0fa469f4aa1fc323794"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.18.3/fir-linux-amd64"
      sha256 "9978761f88ebe2558d2ae26cb5d43c85c9b67a09d2c41d09bca8e9c218ae40e9"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.18.3/fir-linux-armv6"
      sha256 "ac52566e9c830878a323e9c66a370ad54701953d8a1b04fc4964220293336798"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.18.3/fir-linux-arm64"
      sha256 "e7ecc6c685729bd728cbbce2660efccec3f0bd240e10554b49927623bf8cea6f"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.18). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.18

      To go back to the rolling latest:
        brew unlink fir@1.18
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
