# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT080 < Formula
  desc "Fast, portable AI coding agent (pinned 0.80)"
  homepage "https://github.com/kfet/fir"
  version "0.80.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.80.0/fir-darwin-amd64"
      sha256 "390dd9eca210c7205da34fa98a41e341ea3ae3f434bd1da84e0c2279f5e26353"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.80.0/fir-darwin-arm64"
      sha256 "ce9939e5402946ad9207bacdc79acc64dd4591b07d0eb5af6c7fe107c83e5f1c"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.80.0/fir-linux-amd64"
      sha256 "1ec774be616ccf9eb9bb4c1b462baa9c55c95ab2a42cdf9d24d68a7e00fd82d5"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.80.0/fir-linux-armv6"
      sha256 "9b6d73d46db94e3ccaf75dbb4d4e97e26a54c26a5645331aa6f67f0ea52ed188"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.80.0/fir-linux-arm64"
      sha256 "63e47c563173ee1a0a4ddef1db536170c1d017a4097a1edc965797a2011ecfa3"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.80). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.80

      To go back to the rolling latest:
        brew unlink fir@0.80
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
