# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT16 < Formula
  desc "Fast, portable AI coding agent (pinned 1.6)"
  homepage "https://github.com/kfet/fir"
  version "1.6.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.6.3/fir-darwin-amd64"
      sha256 "4e4984d7833ecb7b21a64615ac023e971b8552ec784b27ec02eea3145c24f41f"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.6.3/fir-darwin-arm64"
      sha256 "9abc4f294905ee928df859db4a8644b227e4b088ccdad7e9a9b58a8eb57bfb4d"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.6.3/fir-linux-amd64"
      sha256 "6be364610ad51857e1e8de2a478b125977c84b6ab89110fedb9b1738a84d4e7a"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.6.3/fir-linux-armv6"
      sha256 "7b619fcaaa032f6d2c0d0297e8102c9ba4670d3d99ffbcd22aeabd1d30cf4f33"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.6.3/fir-linux-arm64"
      sha256 "68daf522c472ccab3ed9c97bca1bf3373c23cbc8257ad9981d44d60f90be172a"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.6). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.6

      To go back to the rolling latest:
        brew unlink fir@1.6
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
