# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT128 < Formula
  desc "Fast, portable AI coding agent (pinned 1.28)"
  homepage "https://github.com/kfet/fir"
  version "1.28.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.28.0/fir-darwin-amd64"
      sha256 "1a5a3392a5df89395dfae04025bc82caa7bd368768adf0eac9011b1451655264"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.28.0/fir-darwin-arm64"
      sha256 "c8021eccefed2ba1b0993cdd1bfe951df89ee95470f6f38e62d93e274e498bd3"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.28.0/fir-linux-amd64"
      sha256 "7158215c255415bd5079948672e6e73733e1eaf804aca71a4011781f9afa4d25"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.28.0/fir-linux-armv6"
      sha256 "cfd0257ab40cea0b0f20c225dbd65e4efe34f8e25809002537afe400fb8b9550"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.28.0/fir-linux-arm64"
      sha256 "2ac05a7abd1742e0f263095c2b9fddab883d6f3455fb03b4e01eccd151c78f80"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.28). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.28

      To go back to the rolling latest:
        brew unlink fir@1.28
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
