# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT19 < Formula
  desc "Fast, portable AI coding agent (pinned 1.9)"
  homepage "https://github.com/kfet/fir"
  version "1.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.9.0/fir-darwin-amd64"
      sha256 "7a3bf8a285ae0362ae779cbf8241694e615350a611f8520b3a94f431134740a2"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.9.0/fir-darwin-arm64"
      sha256 "1c24b65d01bf6b888b292f121b5f2cb94db1e243581b9e4b53a08cace4b1a280"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.9.0/fir-linux-amd64"
      sha256 "fbc82500b1ebaa35dde92336bb640af75d137ba3a2f93fdfd183cb1e0f645f97"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.9.0/fir-linux-armv6"
      sha256 "cd38130b3613a169241ada0234b04104e9a129ab1c4e3000029b34b8b62915a9"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.9.0/fir-linux-arm64"
      sha256 "3cdeaaa122b1bea87a0fe8b6c7b88683a62e1da5a9515f2a48bb3aa910047bc0"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.9). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.9

      To go back to the rolling latest:
        brew unlink fir@1.9
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
