# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT117 < Formula
  desc "Fast, portable AI coding agent (pinned 1.17)"
  homepage "https://github.com/kfet/fir"
  version "1.17.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.17.0/fir-darwin-amd64"
      sha256 "a1e3afe5fbc264c0fb9faf9b0695738864983ad6771e2830c34304268d1b2613"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.17.0/fir-darwin-arm64"
      sha256 "6c99d4ec0e824e2192321fa4674bb61c30340035f37844229d303f2d508f3140"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.17.0/fir-linux-amd64"
      sha256 "120ecaa96fa0d16183299d367b21338626c38879ca7dfdc7e461315f5e885b5e"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.17.0/fir-linux-armv6"
      sha256 "f62163291726d52e605338718b94d966faf4b05158f3e6d464189b388f8c9a7a"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.17.0/fir-linux-arm64"
      sha256 "2989e876201e9f444e1237aabfab1a40327bee3bf13fc33af5b8084536d6c13d"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.17). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.17

      To go back to the rolling latest:
        brew unlink fir@1.17
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
