# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT091 < Formula
  desc "Fast, portable AI coding agent (pinned 0.91)"
  homepage "https://github.com/kfet/fir"
  version "0.91.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.91.0/fir-darwin-amd64"
      sha256 "9f25a81e501681ef4890ab7f1e2afb1f41496ff8ee0c4a20b784bd88ab0cfc1f"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.91.0/fir-darwin-arm64"
      sha256 "6e469314551f0b7ce3e8ee60205f1934dc1b7e8845ef1b040dac6826cfa565da"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.91.0/fir-linux-amd64"
      sha256 "6d778642643bc8f000adc49ad9f83d50f42500b1b162dcfc0eb2cd3438dcff94"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.91.0/fir-linux-armv6"
      sha256 "f2c8affe630c54d6aa6f8d440eabb3c32e8f3c24bf0e617d9b80ee4a1dd88f94"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.91.0/fir-linux-arm64"
      sha256 "e3a65ed2e96f1e8aa2f034f4c932590d35a4c4c33f651234198d0c608266d946"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.91). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.91

      To go back to the rolling latest:
        brew unlink fir@0.91
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
