# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT129 < Formula
  desc "Fast, portable AI coding agent (pinned 1.29)"
  homepage "https://github.com/kfet/fir"
  version "1.29.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.29.1/fir-darwin-amd64"
      sha256 "f659ce95319b0da0e981fad346d352b7b8fd5bf150c25720db5cbb4b743fb172"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.29.1/fir-darwin-arm64"
      sha256 "775171e0a02c0a263d6e33dc5b40b897e1f253a881b2d78bb48ba9bf2d2865eb"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.29.1/fir-linux-amd64"
      sha256 "9cfdf7a8cc818c73b6c724566bfa5f6c5dd955f5b5e53e865dce14cd6e82a7d0"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.29.1/fir-linux-armv6"
      sha256 "3a31abfa91e38300611298308d86f690ee89b2c4824b10078eac652666de7a19"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.29.1/fir-linux-arm64"
      sha256 "65468ac95c8addaf316bfb504d948e2c8dfcd72bb01e9dff61bcef015891d396"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.29). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.29

      To go back to the rolling latest:
        brew unlink fir@1.29
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
