# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT084 < Formula
  desc "Fast, portable AI coding agent (pinned 0.84)"
  homepage "https://github.com/kfet/fir"
  version "0.84.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.84.0/fir-darwin-amd64"
      sha256 "7a284f2813bfd4ef340270760300a892e5e7fbc044b050c8298a9be5cdcecf75"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.84.0/fir-darwin-arm64"
      sha256 "1d20d7f3d67885e7a93a34d5a9544cabeb2eb4e16edbb784018f38a90de9d7dd"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.84.0/fir-linux-amd64"
      sha256 "337282c52bb2d40757ab075a1b4d3def35596ab5f8f9bdf2af44ee64a24d4cad"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.84.0/fir-linux-armv6"
      sha256 "2bcf91113750655aa9ceffebee634c1ed3a32047835938fdff12c8e92ba30c3e"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.84.0/fir-linux-arm64"
      sha256 "421c7c49df2d1dc554072b99c5de0ba9efa38ea3b70d48eaba64fead6aa17c93"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.84). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.84

      To go back to the rolling latest:
        brew unlink fir@0.84
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
