# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT13 < Formula
  desc "Fast, portable AI coding agent (pinned 1.3)"
  homepage "https://github.com/kfet/fir"
  version "1.3.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.3.4/fir-darwin-amd64"
      sha256 "17dc2d89ea4751f00eba04a46cd4e4672a2502d89e8f82d7c79dee5fecca07cd"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.3.4/fir-darwin-arm64"
      sha256 "498055075a900ac85e2d921135c0a9296ec675c8b38cd202638f346223fd85fe"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.3.4/fir-linux-amd64"
      sha256 "3e9c2733b4ca961e2c0bc02ed2a27bc10335a9fd3edd4c5c30e4e7bf99051f50"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.3.4/fir-linux-armv6"
      sha256 "4c4d09d360bc1b019892de966dfc4043b696194116319505a3941c57b1c1925d"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.3.4/fir-linux-arm64"
      sha256 "e0eded0be73fbf702fe5288db93550bef4c591a59389127b610a0a907df318ec"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.3). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.3

      To go back to the rolling latest:
        brew unlink fir@1.3
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
