# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT131 < Formula
  desc "Fast, portable AI coding agent (pinned 1.31)"
  homepage "https://github.com/kfet/fir"
  version "1.31.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.31.1/fir-darwin-amd64"
      sha256 "01f96c5f3c8cb5d9e45eddb83dc352154691484577e27019d868cad02248f722"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.31.1/fir-darwin-arm64"
      sha256 "da92a3743e94f1d8193f694b564718c893a5cf50160c57d1c8b0cd2ebc7453f9"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.31.1/fir-linux-amd64"
      sha256 "ea700e6bf8ee56bc2dd878e846ed01ddcd15b9580e319deea36b2100deea23af"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.31.1/fir-linux-armv6"
      sha256 "8adbbdbb5377b9d7ffe48c1719f729b12cc1039bee8fada7e1c162cfdba5256a"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.31.1/fir-linux-arm64"
      sha256 "f1f1a79e2f1f57efc1c78e648429087df7136f93eea324f52ad35dbc32748d4e"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.31). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.31

      To go back to the rolling latest:
        brew unlink fir@1.31
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
