# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT098 < Formula
  desc "Fast, portable AI coding agent (pinned 0.98)"
  homepage "https://github.com/kfet/fir"
  version "0.98.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.98.3/fir-darwin-amd64"
      sha256 "6a8b59bdd02c66c6a5f4425f1698bb87e8326961218d0e9115f0ea168d36f2d0"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.98.3/fir-darwin-arm64"
      sha256 "7bf55c7cab99b188bbe37391e8f1fa4761405ab66b6114fea764bc1309c7927e"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.98.3/fir-linux-amd64"
      sha256 "45d7041e2ff97647ccd4a99cb6a4d564acdefbb356c482e48abf39188f38ff97"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.98.3/fir-linux-armv6"
      sha256 "3f1a3b91e1c2eb730c4400d40b8997278944d3a459dd4f5d99fdb1cd298e4608"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.98.3/fir-linux-arm64"
      sha256 "411787ed71e323685efa204bf524067b94d0d07f14da58a50257b8748e705459"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.98). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.98

      To go back to the rolling latest:
        brew unlink fir@0.98
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
