# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT116 < Formula
  desc "Fast, portable AI coding agent (pinned 1.16)"
  homepage "https://github.com/kfet/fir"
  version "1.16.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.16.0/fir-darwin-amd64"
      sha256 "b63e96ba8cb46d79b1a077f3dceac9a63c08e56ba182c7cf725ed475b0c16e7f"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.16.0/fir-darwin-arm64"
      sha256 "cc09d2e96f35a6319eefa19ec469c4576a2379e55f1279a71e14ad3b6ef836f3"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.16.0/fir-linux-amd64"
      sha256 "d14b50cf8bb9c92edf81251e8f7dff1114df3c6dfd93e6fc6b0b3b2adfe03775"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.16.0/fir-linux-armv6"
      sha256 "da550dbce9cfc915364aad2cd78e25e55bce01882f1a2cc2ea58ef1d8d126490"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.16.0/fir-linux-arm64"
      sha256 "f94fc85dc1755709f546fd3066954c438b2be7943a68ab5ef04d1135e36de5f8"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.16). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.16

      To go back to the rolling latest:
        brew unlink fir@1.16
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
