# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT067 < Formula
  desc "Fast, portable AI coding agent (pinned 0.67)"
  homepage "https://github.com/kfet/fir"
  version "0.67.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.67.0/fir-darwin-amd64"
      sha256 "db1b20a2846d508ab20890d712559aea4926193cc33d64f5918582821dda057a"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.67.0/fir-darwin-arm64"
      sha256 "ab0cb5a25f7cf93f3554cfc36f596bbaa662ed53f26db783951eda9e0e83e30f"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.67.0/fir-linux-amd64"
      sha256 "cf0d79810db07affe293e35edec226e5cd470d198b136808c52c34dec99e5722"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.67.0/fir-linux-armv6"
      sha256 "f9508c55b158dc4483e0fdb957f0c532504274cef9a39d543769e2961e4be287"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.67.0/fir-linux-arm64"
      sha256 "06904450f9ccc2d5aacd12dd5c36fa8d0c34288e411975f21e97111d66581abd"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.67). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.67

      To go back to the rolling latest:
        brew unlink fir@0.67
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
