# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT133 < Formula
  desc "Fast, portable AI coding agent (pinned 1.33)"
  homepage "https://github.com/kfet/fir"
  version "1.33.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.33.0/fir-darwin-amd64"
      sha256 "1371c43a4e2ca45317f6ddfc7003e70c4c249c79810d1edb9a526f6db0fd35dd"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.33.0/fir-darwin-arm64"
      sha256 "2d5aa63d0cdc2ca0e3efdaa1840fccf1d1023fbc0ecaf3c48d38d29ca51174fd"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.33.0/fir-linux-amd64"
      sha256 "ded4bd98973f4d23b289d683224c0e9e55192ed91b2e92781e566da8a89e48ef"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.33.0/fir-linux-armv6"
      sha256 "a1996c248be612079e685c345aafa0fbdad9944e5f2683d87830bfff36e073f4"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.33.0/fir-linux-arm64"
      sha256 "67ffb8668ebf83f1c06309024d934cc111a0ef8894e40eaf48b115b37541147c"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.33). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.33

      To go back to the rolling latest:
        brew unlink fir@1.33
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
