# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT126 < Formula
  desc "Fast, portable AI coding agent (pinned 1.26)"
  homepage "https://github.com/kfet/fir"
  version "1.26.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.26.0/fir-darwin-amd64"
      sha256 "3330f7af9d8bea372a7c70ed7533fc41656bfa86ccb548d3ea450bdb3223823d"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.26.0/fir-darwin-arm64"
      sha256 "b488137855fa12185cda274a4e9eef1f0ce196022f4be94cafe59758d3dcf67c"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.26.0/fir-linux-amd64"
      sha256 "5e6f800c05f99c934558bcd0fd471feaf43d57eb9123905eb0ce61bb242c7111"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.26.0/fir-linux-armv6"
      sha256 "1d23a0f7652e3966c38f0e93dc593eeb7d26e558b17df4e35a16fc009d5b2154"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.26.0/fir-linux-arm64"
      sha256 "d06156c3bcce532a18ac6d285642c489c3d26cdd074a3027e5c43c1c49d4c13a"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.26). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.26

      To go back to the rolling latest:
        brew unlink fir@1.26
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
