# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT123 < Formula
  desc "Fast, portable AI coding agent (pinned 1.23)"
  homepage "https://github.com/kfet/fir"
  version "1.23.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.23.0/fir-darwin-amd64"
      sha256 "72ef23391b6e9aca0586f3e56d63bbc582045cafdd4c34e2e0d15499d404a274"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.23.0/fir-darwin-arm64"
      sha256 "1250e8ab29c2de560bb2f5a1199ab2cb22c0663d3f4facc941629523ec86c776"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.23.0/fir-linux-amd64"
      sha256 "9bbaef891da0b2fa70bbc19d599c2526088ee993ff282c740b47614c24fd631c"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.23.0/fir-linux-armv6"
      sha256 "d16fbcdd66330c3f79348a1358eca02e944cdb638cd8bde13f334290f302951d"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.23.0/fir-linux-arm64"
      sha256 "4866eaaa85caa10e9b3164ec7e20e6a38a99beb562575b43f50e96c8926a5070"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.23). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.23

      To go back to the rolling latest:
        brew unlink fir@1.23
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
