# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT067 < Formula
  desc "Fast, portable AI coding agent (pinned 0.67)"
  homepage "https://github.com/kfet/fir"
  version "0.67.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.67.2/fir-darwin-amd64"
      sha256 "8be26a34c190cca1360ab8426ff3b5267a56067628f18d1c14e084ea8fd0158c"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.67.2/fir-darwin-arm64"
      sha256 "52faa0178cf01279bcbf3e7e90c4dfadc94a1358301f1a4dc87fabc17f0968f3"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.67.2/fir-linux-amd64"
      sha256 "500bea5886a4b5aa78d7159a4f9cf55a12712bc67674921965aa04c2f21c5ff9"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.67.2/fir-linux-armv6"
      sha256 "97e761024a299097ed7f303e98e823e4862864f99e923da6d6b3e61b97b99735"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.67.2/fir-linux-arm64"
      sha256 "4fb661e516b8b66db51efe22c49d5a41c14af2206c8f62b91835e5088efb1c46"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.67). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.67

      To go back to the rolling latest:
        brew unlink fir@0.67
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
