# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT14 < Formula
  desc "Fast, portable AI coding agent (pinned 1.4)"
  homepage "https://github.com/kfet/fir"
  version "1.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.4.2/fir-darwin-amd64"
      sha256 "4d65d70c2bf60a9ee10cef212836d595a49622a365f575debc450445ab92b28b"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.4.2/fir-darwin-arm64"
      sha256 "ebb506cad2da60e5ba52702af28dfd9e2cf80b4f1f44b7ea8e904424a9ade352"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.4.2/fir-linux-amd64"
      sha256 "1d5acf59913dc7472c2de6d4cfa30bbfe0b686dd72c38e77e6f996457888037d"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.4.2/fir-linux-armv6"
      sha256 "bc00d85a3d50a4e7e6c795e1ccb262aa340c6ea09c15eb8941662ad1d549aa6a"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.4.2/fir-linux-arm64"
      sha256 "8e06c3d92beba4a6cdc1dfaf06d9e84356fad96eac7d571457875dc46518e21f"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.4). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.4

      To go back to the rolling latest:
        brew unlink fir@1.4
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
