# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT087 < Formula
  desc "Fast, portable AI coding agent (pinned 0.87)"
  homepage "https://github.com/kfet/fir"
  version "0.87.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.87.0/fir-darwin-amd64"
      sha256 "a4f80b00a700238e826587b25261d9c632168fea28710344442115464b5be955"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.87.0/fir-darwin-arm64"
      sha256 "858f731b256fd2c0f97ad107cd37de70bb8fbac8c34144b68e494d7c79c14686"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.87.0/fir-linux-amd64"
      sha256 "19fff60a6380e4107758c60abb7ce7f685d23ce6ea5e2f4d1ee5d15156452f7c"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.87.0/fir-linux-armv6"
      sha256 "fbcd2cc2696511c415e37a658a27caf3e2df05a07c32a9e68e745b55ab36828d"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.87.0/fir-linux-arm64"
      sha256 "a96c852e1d36e3df1850112b3679845b5b7c0f55a0eafda23bb780916d274c39"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.87). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.87

      To go back to the rolling latest:
        brew unlink fir@0.87
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
