# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT13 < Formula
  desc "Fast, portable AI coding agent (pinned 1.3)"
  homepage "https://github.com/kfet/fir"
  version "1.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.3.3/fir-darwin-amd64"
      sha256 "2bb88cb67b8cce9424c31c521ad0cc83a899c687a7aa9c17000e82e11d0bce53"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.3.3/fir-darwin-arm64"
      sha256 "aa390e9cf83ba5bb7f00cca4dc57a6c64fa611a14a9e2d6bb291d307a8a2658e"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.3.3/fir-linux-amd64"
      sha256 "e350e14dfa42fee5448ed599cbcc26f0895763133d0d5bf094b6f625cf7cb622"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.3.3/fir-linux-armv6"
      sha256 "b7a4565976356d6b9d31c29ae672349bf85e368f8922eabc9639aaf0515b2e31"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.3.3/fir-linux-arm64"
      sha256 "6051d27d614a26252e389c13d7524f807d1947cf08deb4a51933c893215cf957"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.3). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.3

      To go back to the rolling latest:
        brew unlink fir@1.3
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
