# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT130 < Formula
  desc "Fast, portable AI coding agent (pinned 1.30)"
  homepage "https://github.com/kfet/fir"
  version "1.30.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.30.1/fir-darwin-amd64"
      sha256 "109ad8ddf109d29197c22be988a89bef2d60198781686460e3ac66d7da561949"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.30.1/fir-darwin-arm64"
      sha256 "0dd08cb4f2c3c9ffb296167b65d550fb2b16ef925e8d9ef1c63ea3ba427b9d34"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.30.1/fir-linux-amd64"
      sha256 "bb538467424b51620e95e01f3a09761ee5cc32979b4474a0201ec0c5afaf9b43"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.30.1/fir-linux-armv6"
      sha256 "81edff34b4e1975b88836d7bdd81c09b0fdb19f36b39ccb3c890576a702bff3e"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.30.1/fir-linux-arm64"
      sha256 "3fa654230c35aedb4509d3492af43251b145cefeefcf862f7be044b499a3745f"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.30). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.30

      To go back to the rolling latest:
        brew unlink fir@1.30
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
