# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT17 < Formula
  desc "Fast, portable AI coding agent (pinned 1.7)"
  homepage "https://github.com/kfet/fir"
  version "1.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.7.1/fir-darwin-amd64"
      sha256 "7b2ef933032256169160a53f4ffe4f9349ac320d43f289c076513e523481af18"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.7.1/fir-darwin-arm64"
      sha256 "d20c507f86da4617ad426e946bbd0b78f351cdd2e19a7c2ab8e74d47bc285976"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.7.1/fir-linux-amd64"
      sha256 "a6356b4c982f457b4c2a755dd3067a65a8f6ef9a6211468a24fe01f5bcfd9433"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.7.1/fir-linux-armv6"
      sha256 "689d4968c6d1ea434ee9a064bfa7a73cbe13a1382ef0a8e9b7bba557408d4393"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.7.1/fir-linux-arm64"
      sha256 "a3ff3c90ea0e1e824d9008c89a095cbf4da81dc85f2cc352126ef20c30dfd32d"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.7). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.7

      To go back to the rolling latest:
        brew unlink fir@1.7
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
