# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT10 < Formula
  desc "Fast, portable AI coding agent (pinned 1.0)"
  homepage "https://github.com/kfet/fir"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.0.0/fir-darwin-amd64"
      sha256 "b87ca4bce5f5818bace9ec4c6f42d7eca140ddb6369a55f32ea9b7fff69fc18e"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.0.0/fir-darwin-arm64"
      sha256 "d6b614ebb14812f218241725545325c7a961a0b8413f5ac53737c624bbe6ec45"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.0.0/fir-linux-amd64"
      sha256 "231e4d6d22d11048a305416136119761d20ccff90f851769736e3ad44f2e5dd9"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.0.0/fir-linux-armv6"
      sha256 "35826838343f0a8347971f93c33a18c66357c8e1d9fbbed859d07d31ee67b66f"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.0.0/fir-linux-arm64"
      sha256 "11bac2b302f766469dc0c2927d62ada524542da3d5b12722c41b78691f2d367b"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.0). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.0

      To go back to the rolling latest:
        brew unlink fir@1.0
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
