# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT18 < Formula
  desc "Fast, portable AI coding agent (pinned 1.8)"
  homepage "https://github.com/kfet/fir"
  version "1.8.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.8.3/fir-darwin-amd64"
      sha256 "4fb9802db7541a4bcf023ec4774d8206efdac5b0053d418dc20daf98b364ca12"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.8.3/fir-darwin-arm64"
      sha256 "e5d15c218d4e973d1a0c64c316bba0cf457345d5cc8b4965df2b42dd79b1178c"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.8.3/fir-linux-amd64"
      sha256 "2480b512fa0d0d7bfd61c1ac99160d061c3b102b0ecf4de5146878ebf4baa3a1"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.8.3/fir-linux-armv6"
      sha256 "ffb9b2c2e8f745e8c4cce0cb404bd42903db3be66b7a63376cd0b349ddde2c9e"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.8.3/fir-linux-arm64"
      sha256 "fe3b0c3a4da19a3a200ab7d7b18a7e054be4ba69b3852c727a5c835c88b42745"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.8). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.8

      To go back to the rolling latest:
        brew unlink fir@1.8
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
