# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT090 < Formula
  desc "Fast, portable AI coding agent (pinned 0.90)"
  homepage "https://github.com/kfet/fir"
  version "0.90.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.90.1/fir-darwin-amd64"
      sha256 "c10f4a43b86dd707742f1b8c5e9a69af9dc26ce757f96b7fac7d09227cbde8fc"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.90.1/fir-darwin-arm64"
      sha256 "fd37dfd1f682faf6aaf92060e1c5aeb70fa2f0898e99756c9e22db843c0fc474"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.90.1/fir-linux-amd64"
      sha256 "f6d18f4b21fd2dad83f1022b744483fb0cab90d055cea4448dd3e9b7f316a3e1"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.90.1/fir-linux-armv6"
      sha256 "3f12e27da5e82df4e4edcbbc7d2acda2eef4b6fc2226ee31bee8da1e185edc48"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.90.1/fir-linux-arm64"
      sha256 "ae3996fab358aa56c44699e28ca6bc7eb87e9490da44f34d803d49a392078505"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.90). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.90

      To go back to the rolling latest:
        brew unlink fir@0.90
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
