# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT110 < Formula
  desc "Fast, portable AI coding agent (pinned 1.10)"
  homepage "https://github.com/kfet/fir"
  version "1.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.10.0/fir-darwin-amd64"
      sha256 "4923ec38cd5437ee854ec7db6a60bfa4994cc8cb624a014d47d2217fb4182f43"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.10.0/fir-darwin-arm64"
      sha256 "9c8954870a116c06367d8d0ad25b1299fbaf103b13421b65a8e32df3d7c2e740"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.10.0/fir-linux-amd64"
      sha256 "ceeaafe776c5d9b64ea02ac9a0be45cc0c1c816591a891a8fd737398d67bc263"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.10.0/fir-linux-armv6"
      sha256 "e3db6186f7253fccd69bc52fbc7262a4698593849da003bc6a836ef1e62da291"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.10.0/fir-linux-arm64"
      sha256 "e412bef300fa936f4941335ae3864d157b2f810485212699a5c46bf1bb9e0f94"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.10). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.10

      To go back to the rolling latest:
        brew unlink fir@1.10
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
