# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT082 < Formula
  desc "Fast, portable AI coding agent (pinned 0.82)"
  homepage "https://github.com/kfet/fir"
  version "0.82.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.82.0/fir-darwin-amd64"
      sha256 "085e6c3a9ddbf3e5268f7f682dbb17d5ac832559b439716f517f7c80f640fa65"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.82.0/fir-darwin-arm64"
      sha256 "49bc4716b0a2fb4842922959b8ff35c043cc4305fb1858be00ff48d3d92beda3"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.82.0/fir-linux-amd64"
      sha256 "bbfed691dbce28a677027ae7607a4f1fba8a7d1cbdfc390f738926598e9ebfbf"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.82.0/fir-linux-armv6"
      sha256 "f3517cf66b06ab50c119b4037a04705c618d065f5aecfd29b18dd2909a21586d"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.82.0/fir-linux-arm64"
      sha256 "4ac9b25c3e846f18f29289cd896bce371784eb3ad65d7100bd5ce83b58686bb9"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.82). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.82

      To go back to the rolling latest:
        brew unlink fir@0.82
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
