# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT073 < Formula
  desc "Fast, portable AI coding agent (pinned 0.73)"
  homepage "https://github.com/kfet/fir"
  version "0.73.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.73.1/fir-darwin-amd64"
      sha256 "d2e6f3d8ab2f59de44ea3a2f1aaff14d529e2d9aabc6384acc16b51121e619a8"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.73.1/fir-darwin-arm64"
      sha256 "ee9ffd5420f2980a7ca480ae816104323b948bfdb0adb9123a9fd197a81bb486"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.73.1/fir-linux-amd64"
      sha256 "760c630a7835544b19f39f3c11899092ebc58d7561b05f49326a086edd43252f"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.73.1/fir-linux-armv6"
      sha256 "3efef60fa8d011c24690f201b7fba484204b717173317dfc1ad94f118ac0a61b"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.73.1/fir-linux-arm64"
      sha256 "7c42fa9bd83108fc81efada0e3d9abc50adc0afb0be06c28e14f0607e45d92f5"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.73). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.73

      To go back to the rolling latest:
        brew unlink fir@0.73
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
