# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT125 < Formula
  desc "Fast, portable AI coding agent (pinned 1.25)"
  homepage "https://github.com/kfet/fir"
  version "1.25.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.25.1/fir-darwin-amd64"
      sha256 "415d10cd3a5b8cb0fc7b7fab78266fb5dddfaddf25ad09161e79e31a481a3fe5"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.25.1/fir-darwin-arm64"
      sha256 "8e8a44104334cbf15e3df454d92fca3ce1cc605fedd6cfee1c274d2f6bd65886"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.25.1/fir-linux-amd64"
      sha256 "486ee0c4b40d20d1ef64c67d92a57de1f8d9784ccce0dd64ed8522b555a46c2f"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.25.1/fir-linux-armv6"
      sha256 "019a864d2a3d232496201ee99974d4252423688976c8434d71fa02e948b86488"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.25.1/fir-linux-arm64"
      sha256 "aa15dbf2889020817e2b8f488f76da25fb8881cce7397120858becd60e974efd"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.25). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.25

      To go back to the rolling latest:
        brew unlink fir@1.25
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
