# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT092 < Formula
  desc "Fast, portable AI coding agent (pinned 0.92)"
  homepage "https://github.com/kfet/fir"
  version "0.92.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.92.0/fir-darwin-amd64"
      sha256 "ac2677e03f0597c222e100d60f23344f115accc4a6ac4567a183174d0fd2a930"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.92.0/fir-darwin-arm64"
      sha256 "1740b3f894a05cd2c22615cbc3544390a76a91b07dfa44f13d6482ecb4c642b8"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.92.0/fir-linux-amd64"
      sha256 "a9a62744fb550dfecb4d7f969cb42aaeafa7231494ef70a82a0dbd96aa619b5f"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.92.0/fir-linux-armv6"
      sha256 "9a9a6d660eb07e1488f871b4996224dfab61757c74e5d9fa34775091ecbc0411"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.92.0/fir-linux-arm64"
      sha256 "fc9db5f78fa008371e4e17a21614aa1ffc17cba6b47e790b27f7c17c6eec1798"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.92). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.92

      To go back to the rolling latest:
        brew unlink fir@0.92
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
