# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT113 < Formula
  desc "Fast, portable AI coding agent (pinned 1.13)"
  homepage "https://github.com/kfet/fir"
  version "1.13.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.13.1/fir-darwin-amd64"
      sha256 "6162130416935221faf2fa61eea0d0e5a83eee5c832f166a802c66aefa5645c5"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.13.1/fir-darwin-arm64"
      sha256 "91bda7d3595977a39fb45d703463757dc977a91bdd7b7763223f699cce1a2799"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.13.1/fir-linux-amd64"
      sha256 "2582dc49013cfd06f18d23b694f2ff962a63245404738bfcbc13b00a21805a94"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.13.1/fir-linux-armv6"
      sha256 "3df21bd8e2ee1ffba354b8a340c64ef7fea4297ae02bfc008624c1be215ce904"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.13.1/fir-linux-arm64"
      sha256 "c861901ff81cebe1572719246149c88e8b450a21af4d9a87bf9b601fb65dda66"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.13). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.13

      To go back to the rolling latest:
        brew unlink fir@1.13
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
