# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT110 < Formula
  desc "Fast, portable AI coding agent (pinned 1.10)"
  homepage "https://github.com/kfet/fir"
  version "1.10.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.10.3/fir-darwin-amd64"
      sha256 "34f21428f967352b02fccf6892a0e17176bf1c9ce68219f52791110f98524853"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.10.3/fir-darwin-arm64"
      sha256 "45cbd5e32a5978ffcdc5521cc27aecfacee2021295a7d543a5e9b3340351cfe4"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.10.3/fir-linux-amd64"
      sha256 "0bebf544e165d654126e1e40bf43d94d80a87fb8c35843a2bbef01b76864c529"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.10.3/fir-linux-armv6"
      sha256 "afa53a66cd96df4eb87ae34b8774ed739f6faf64f19bd2730942117722f51288"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.10.3/fir-linux-arm64"
      sha256 "3d69b00e95573d92e55fabf6fa649f6916725e3fde6fc284ff27ff41a216e50f"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.10). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.10

      To go back to the rolling latest:
        brew unlink fir@1.10
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
