# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT099 < Formula
  desc "Fast, portable AI coding agent (pinned 0.99)"
  homepage "https://github.com/kfet/fir"
  version "0.99.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.99.0/fir-darwin-amd64"
      sha256 "114467f6a9b3f1cb8ec7db41e7ffbd94c8cf0d043fcf947fc2c3d68e4c8d8228"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.99.0/fir-darwin-arm64"
      sha256 "0e9024c3899ba022942a80ff51d6b1ad6455e70fe6495bc70bb08a12d45d1208"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.99.0/fir-linux-amd64"
      sha256 "f3a3c1607becefbb268ae71a40a308ab8458fd27ae871dafec53c32ea103d1cd"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.99.0/fir-linux-armv6"
      sha256 "3be4820f4a3f2db62adc5a8602405bdab55d353ffc90307183441fd3744ab872"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.99.0/fir-linux-arm64"
      sha256 "2a92761e808664e6770ff6c4f127fee5819ce954d27b7269c3f21d5fe2155b15"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.99). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.99

      To go back to the rolling latest:
        brew unlink fir@0.99
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
