# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT086 < Formula
  desc "Fast, portable AI coding agent (pinned 0.86)"
  homepage "https://github.com/kfet/fir"
  version "0.86.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.86.0/fir-darwin-amd64"
      sha256 "ce3ecddd07cd458dbffd506f94b7df0d82d7a93baeaf19524d20409d9df8249f"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.86.0/fir-darwin-arm64"
      sha256 "5c416da22e768bf118f6357ee25a27b7161746ccec81a1c60147b560a22aa471"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.86.0/fir-linux-amd64"
      sha256 "04bdae148f111185c9c61fb193d1fca3702ee6494b8919b9c8f433639dfbb894"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.86.0/fir-linux-armv6"
      sha256 "d1004fdb751da21cb3795a3e9024de934f47e3ea06be54d82b51ad2be37c92d5"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.86.0/fir-linux-arm64"
      sha256 "109b66a70caa2ecce1be999f9689623c62f601fec34ecec3f9077149ae9ad630"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.86). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.86

      To go back to the rolling latest:
        brew unlink fir@0.86
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
