# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT098 < Formula
  desc "Fast, portable AI coding agent (pinned 0.98)"
  homepage "https://github.com/kfet/fir"
  version "0.98.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.98.1/fir-darwin-amd64"
      sha256 "9aec94040169e41cbc644782ddd1eb1ab1c8690f0e1fc9b09ae1efa9c715e132"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.98.1/fir-darwin-arm64"
      sha256 "cdb80772401348dc38ab4cda02e468a27d57fe206131fee9ad911a44ea52bac5"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.98.1/fir-linux-amd64"
      sha256 "b24211cd3323b3146c84d9724a6d7ca0815583b4f696e505506070039ebb2eab"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.98.1/fir-linux-armv6"
      sha256 "7b12404d0335e2e67a56e4b3640fc513aacb07de615143f911e6fb47437cff92"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.98.1/fir-linux-arm64"
      sha256 "13f032e30a39758f8844cae720af091956a92debbd1b33562a84196e7577cc72"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.98). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.98

      To go back to the rolling latest:
        brew unlink fir@0.98
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
