# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT073 < Formula
  desc "Fast, portable AI coding agent (pinned 0.73)"
  homepage "https://github.com/kfet/fir"
  version "0.73.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.73.0/fir-darwin-amd64"
      sha256 "191c798f7a69844a29bde6dde01fb8dd5ce0dfe89bd02705a29ec6879f0beddf"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.73.0/fir-darwin-arm64"
      sha256 "4ff2f0972f65616c246babe3249df153705690ea3f00c8e15c677922da2f2e61"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.73.0/fir-linux-amd64"
      sha256 "ac859554413654c8a20c93483673fa1ebca59751c35cea259e2a1a4ebebe904e"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.73.0/fir-linux-armv6"
      sha256 "d9e8936105eb5d575dce02b1db41e4c68c0769c21a52b7e40273b75513ffb5a4"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.73.0/fir-linux-arm64"
      sha256 "b6eff08e290347017198bdae0fb0715d9a45ff32f6c2059ca55723abe2dab8b9"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.73). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.73

      To go back to the rolling latest:
        brew unlink fir@0.73
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
