# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT120 < Formula
  desc "Fast, portable AI coding agent (pinned 1.20)"
  homepage "https://github.com/kfet/fir"
  version "1.20.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.20.0/fir-darwin-amd64"
      sha256 "783d8ba44a90b4ccae1ffc38c503c9cb46adde241498d6447b308651c7ef1766"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.20.0/fir-darwin-arm64"
      sha256 "5a76964b0691acb5bb0829b2ae7db7ab4a647fbd65a0957a188a0b39a21b48ba"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.20.0/fir-linux-amd64"
      sha256 "7bf6bedfd1739813cbc6790bfedf502e9aa0c8be4a5510eda8497c25a3b05007"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.20.0/fir-linux-armv6"
      sha256 "f1b3087294cc27b47c13ef814632dc2c2917c7ee9e03a357495167c211a30f52"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.20.0/fir-linux-arm64"
      sha256 "cb328bd9877eb19ab0e1ad7ebe7f0296b856366466fa8d827830e16431d8f174"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.20). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.20

      To go back to the rolling latest:
        brew unlink fir@1.20
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
