# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT118 < Formula
  desc "Fast, portable AI coding agent (pinned 1.18)"
  homepage "https://github.com/kfet/fir"
  version "1.18.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.18.1/fir-darwin-amd64"
      sha256 "fa46978856aa1fbb0f3e805a29aaa4e60978d2751187dcab22a6c9102883762b"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.18.1/fir-darwin-arm64"
      sha256 "1b38bfead5f884565d769ab20a4720aff749b005556091b07111c465afee7ac6"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.18.1/fir-linux-amd64"
      sha256 "50d1e7779dbff123bb404079e28e4f6f6c5f951ef5a1436055783d9186b38968"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.18.1/fir-linux-armv6"
      sha256 "cf4bba0194eceb7b0e8a6018d9d3d166c6dc2d55a3a63636b4169d1567dedcc2"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.18.1/fir-linux-arm64"
      sha256 "58596ebe6fd4491ba59ebbb81cc9c30b7eb856a25df6d2bcd2e7233f813e790c"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.18). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.18

      To go back to the rolling latest:
        brew unlink fir@1.18
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
