# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT080 < Formula
  desc "Fast, portable AI coding agent (pinned 0.80)"
  homepage "https://github.com/kfet/fir"
  version "0.80.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.80.1/fir-darwin-amd64"
      sha256 "02c324315628f4eb83f61c603a36e2f8011ba49a2cf68a1247d6b7de477b4d14"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.80.1/fir-darwin-arm64"
      sha256 "a7c7c921f960ca389905de4fab7c28ac18c94bd3a6baecdaa33519798ccf2a50"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.80.1/fir-linux-amd64"
      sha256 "0b03fe620f27bae445229f0bfbbfe4f440fe934e8feeea9c59372b9a671b76f0"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.80.1/fir-linux-armv6"
      sha256 "b78abdb3974750fab64066457a69cc41df580c4ea91046518ac1ca8f16910203"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.80.1/fir-linux-arm64"
      sha256 "999afa58c1c313f0ac8fdb978be5e697277fac831b28a2e2d341a655210829a0"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.80). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.80

      To go back to the rolling latest:
        brew unlink fir@0.80
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
