# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT064 < Formula
  desc "Fast, portable AI coding agent (pinned 0.64)"
  homepage "https://github.com/kfet/fir"
  version "0.64.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.64.1/fir-darwin-amd64"
      sha256 "d8cae0a57f97f650968b33a6679f63bd506fcb534f233d84bf300c2d3433711d"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.64.1/fir-darwin-arm64"
      sha256 "b82325f9e78bf51dbf4d9e2eb40efc2835d746bff0279dd31b51fcf173b6605e"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.64.1/fir-linux-amd64"
      sha256 "293d45d2ceadb93ce6381eb2343bb395a7a6c330b555d60ca6e8ca36ea025534"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.64.1/fir-linux-armv6"
      sha256 "310d8ced0f82052c89156e27176cfc747384a4e6e48fc848029d6b29c2b62e89"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.64.1/fir-linux-arm64"
      sha256 "c9d6d1f51fe63a275143558c141d599d252ec96e44cf6fcf8c2d2381299e43b1"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.64). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.64

      To go back to the rolling latest:
        brew unlink fir@0.64
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
