# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT118 < Formula
  desc "Fast, portable AI coding agent (pinned 1.18)"
  homepage "https://github.com/kfet/fir"
  version "1.18.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.18.4/fir-darwin-amd64"
      sha256 "d273946fbee5b35822129015301073ac3567d2de937b8f1c38939f30231462d2"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.18.4/fir-darwin-arm64"
      sha256 "08d600aad1778938e96f866cd375302cde5cbfa0cfbfa0eb724d5343a7214413"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.18.4/fir-linux-amd64"
      sha256 "c86d6769149f8980fab9907cacb6d89b2e22a97983ceef4c6a0ecf5e7d22833a"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.18.4/fir-linux-armv6"
      sha256 "82215528188d96726c6ee1d0f635a245a429a5863b77e3c21b2c34ae3a546963"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.18.4/fir-linux-arm64"
      sha256 "d4eecc80858df62b62ff1f49ac431582c153952b0fd3690658fb1bf8183e2ca8"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.18). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.18

      To go back to the rolling latest:
        brew unlink fir@1.18
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
