# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT18 < Formula
  desc "Fast, portable AI coding agent (pinned 1.8)"
  homepage "https://github.com/kfet/fir"
  version "1.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.8.0/fir-darwin-amd64"
      sha256 "67470bbfc8c0d0c5b05fb1660857e671620ad6eda0b8bfc7d0288f7898220bc1"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.8.0/fir-darwin-arm64"
      sha256 "1326bc17c227d060cd7c0455e9cd1c9c50930bfa8811b523961a97198d786a73"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.8.0/fir-linux-amd64"
      sha256 "22acd39ca574ef5d43494b051c367dd0bdf81e9cb92a93707f3c62cf618df1eb"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.8.0/fir-linux-armv6"
      sha256 "9bbd943212ade80d83b8b52050f8509a330ac7622c7effe8b4090b6ca8fa8d3e"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.8.0/fir-linux-arm64"
      sha256 "2498d546017b7852d742861cedfb8cff5ffcdaa097d2ec6a39564d09702f5f56"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.8). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.8

      To go back to the rolling latest:
        brew unlink fir@1.8
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
