# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT124 < Formula
  desc "Fast, portable AI coding agent (pinned 1.24)"
  homepage "https://github.com/kfet/fir"
  version "1.24.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.24.1/fir-darwin-amd64"
      sha256 "76a3e360b40ddcd6252ce5d11ddc0a19f55cf1627e728e337cfb2e70064a1a94"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.24.1/fir-darwin-arm64"
      sha256 "a0b12e52a0558716566ed87f4d3ab794b33d1eae4e6b354fce0c8e6b2ec7a560"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.24.1/fir-linux-amd64"
      sha256 "a8768d20f4c070a821da625e07772e6f1de42e2b61ed72524fdf1553857bde9c"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.24.1/fir-linux-armv6"
      sha256 "22095d2b1b1543ad0dbb167a004f793817196d7517b86215168e32182890f753"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.24.1/fir-linux-arm64"
      sha256 "417fc8f77253a8562aa808219a965c866f6a4d645a876172d2e102092acb70a4"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.24). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.24

      To go back to the rolling latest:
        brew unlink fir@1.24
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
