# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT079 < Formula
  desc "Fast, portable AI coding agent (pinned 0.79)"
  homepage "https://github.com/kfet/fir"
  version "0.79.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.79.0/fir-darwin-amd64"
      sha256 "67a1c4e13b8d2d94eb5de26be0ba6a41ccbd71bedc9d15519cba1c51ee94c1e5"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.79.0/fir-darwin-arm64"
      sha256 "2415f031c9340553481d990c0585a225827638fef57f6e58a7eaaa472c8d01ef"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.79.0/fir-linux-amd64"
      sha256 "45920eac9e24823330af577327d42f8efdafd2f99c6041a6259089b26fe5b7a0"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.79.0/fir-linux-armv6"
      sha256 "e5f53dd94451d27f5018fe306f0c5ef43b8539caf9e9b39a62a836279c394126"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.79.0/fir-linux-arm64"
      sha256 "7a56402261bcc8a70cca243b21c3126fd1aa0f89309cc3eb394fab779137f754"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.79). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.79

      To go back to the rolling latest:
        brew unlink fir@0.79
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
