# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT049 < Formula
  desc "Fast, portable AI coding agent (pinned 0.49)"
  homepage "https://github.com/kfet/fir"
  version "0.49.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.49.0/fir-darwin-amd64"
      sha256 "67a66699ef2590e98a7259e4501847d4138b000850bcda1da9c897e6d0970ef4"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.49.0/fir-darwin-arm64"
      sha256 "6d74177fcd3e42a41c46d190fd174dfd21bc01531d4220069ffaf09f46fd1ba0"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.49.0/fir-linux-amd64"
      sha256 "6bf283aa7162d1ff0e8ed4ad23bef012716c17ab126bd1b1b25c208364de1ee8"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.49.0/fir-linux-armv6"
      sha256 "47df138fe198a0e47a4c243d5d0bca5709cc6b12c066f77576707595120a3d6d"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.49.0/fir-linux-arm64"
      sha256 "37dcfc3a1a214335144e5196ab4890da182a465251b68fb5a4c3b7b219353939"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.49). It ships
      its own bin/fir, which collides with the rolling kfet/fir/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.49

      To go back to the rolling latest:
        brew unlink fir@0.49
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
