# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT120 < Formula
  desc "Fast, portable AI coding agent (pinned 1.20)"
  homepage "https://github.com/kfet/fir"
  version "1.20.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.20.1/fir-darwin-amd64"
      sha256 "05b64bcc957aad5f6a27666befa870a8e4341a194ad78591952142785617d849"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.20.1/fir-darwin-arm64"
      sha256 "4595ba4f61bc88d2404b02357b2197371bf54b1de130d1ca66b70bf944b4e8b5"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.20.1/fir-linux-amd64"
      sha256 "e511bd232c8fc04985f5716d1dc5bf7de233c7076cb18ccb97adc36c972cfa1c"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.20.1/fir-linux-armv6"
      sha256 "cdd4cd19c314b7e42dc2028f513b6ff69d1d5a05b811de085d60127b0f3c090a"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.20.1/fir-linux-arm64"
      sha256 "e8299e81d3a5522248be8465a415dd08e66d55756e422372cfcfe982a23eaa1e"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.20). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.20

      To go back to the rolling latest:
        brew unlink fir@1.20
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
