# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT099 < Formula
  desc "Fast, portable AI coding agent (pinned 0.99)"
  homepage "https://github.com/kfet/fir"
  version "0.99.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.99.1/fir-darwin-amd64"
      sha256 "730fda5271302c4209c53f52d21be8ad655271870803fc2558ce47ebf267e180"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.99.1/fir-darwin-arm64"
      sha256 "59a835b503c65f79e773d65fffecd07d44b6376c3c6456fe0375411680e8b866"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.99.1/fir-linux-amd64"
      sha256 "a5dfc3f8ee40cacd0304c38eab89302e5ed86fcfc1a2e9eb48fd00b5078ba9ce"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.99.1/fir-linux-armv6"
      sha256 "7e6a84f828a25cfe12a1a30d5392d1b03cdb2fc80e62ce0924d372743e3d2751"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.99.1/fir-linux-arm64"
      sha256 "bdfd76a21ddc94f6cccea2d4dbe37f879912d1dd7c6eaf9c0170799268c32a7e"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.99). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.99

      To go back to the rolling latest:
        brew unlink fir@0.99
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
