# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT130 < Formula
  desc "Fast, portable AI coding agent (pinned 1.30)"
  homepage "https://github.com/kfet/fir"
  version "1.30.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.30.3/fir-darwin-amd64"
      sha256 "dfaaf2b684c97a923d92bdf8f1dd9f038a3e9b922c7b157b470145ba49c41f0b"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.30.3/fir-darwin-arm64"
      sha256 "53646f4d18e0633e0478fa87cff5314e6ecbb100a2ea761c8f505cfeaabbb9b8"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.30.3/fir-linux-amd64"
      sha256 "d92b2f7c83f56a889a15218aebb3e10b50097dd90329b7066d5584fea60de22b"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.30.3/fir-linux-armv6"
      sha256 "88036a6da0a86be380bbed7b5c09ea00cac9903aa14bc6b99715cea05261122a"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.30.3/fir-linux-arm64"
      sha256 "559adc59d52c29fda03d381fc4118d889d6a133055b7b440fbe27facb127f238"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.30). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.30

      To go back to the rolling latest:
        brew unlink fir@1.30
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
