# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT13 < Formula
  desc "Fast, portable AI coding agent (pinned 1.3)"
  homepage "https://github.com/kfet/fir"
  version "1.3.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.3.6/fir-darwin-amd64"
      sha256 "b064a9986aa39f742016a872e74020a38cc22e189a89c72d8717eaac35dd439b"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.3.6/fir-darwin-arm64"
      sha256 "ee9221e40e4a0e533a27b8335ebc84fa84a277fd349d1f9bacaed303942b8325"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.3.6/fir-linux-amd64"
      sha256 "97e3faaec1738c05e4f2d96e05fb7b2e14dca485b12185712a0034a43ad40f5f"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.3.6/fir-linux-armv6"
      sha256 "9b41353eea832ffa2b4f1a03216ebf3a6f6ad7673e9df37996bb806fbf9c9513"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.3.6/fir-linux-arm64"
      sha256 "af330f12bc883ae5059f9c6ea42f62c30afc891646cd7e603b1e722f7b680cb8"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.3). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.3

      To go back to the rolling latest:
        brew unlink fir@1.3
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
