# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT076 < Formula
  desc "Fast, portable AI coding agent (pinned 0.76)"
  homepage "https://github.com/kfet/fir"
  version "0.76.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.76.0/fir-darwin-amd64"
      sha256 "899130d35f4f391281c2f18c35b8713a93e9066e489fb36067e8f4a5fccb8c74"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.76.0/fir-darwin-arm64"
      sha256 "96054f5f84e6acc246fda3eeeb752f37022d1b6536e480c55bb2d463a58451f9"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.76.0/fir-linux-amd64"
      sha256 "cb250bcc64978503b363ebbdd56b90790a3face10ed6f46ea63d9f6f8a9f8ebb"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.76.0/fir-linux-armv6"
      sha256 "7f9e747d227147bd5cc33312073b6da57cd215df0704c9fa2088c406c40305dc"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.76.0/fir-linux-arm64"
      sha256 "f1e71c12e4ad7336ae2394e067373d58271e4d6d43a2213a326299bd85d6fb6a"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.76). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.76

      To go back to the rolling latest:
        brew unlink fir@0.76
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
