# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT115 < Formula
  desc "Fast, portable AI coding agent (pinned 1.15)"
  homepage "https://github.com/kfet/fir"
  version "1.15.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.15.0/fir-darwin-amd64"
      sha256 "003f980482b2e093b8881dcd3b3bdc502e3dc5ac19cabf800ac39d2203a43716"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.15.0/fir-darwin-arm64"
      sha256 "e1314ced40f80759d235aff1efeea5aa9995ab450d2fe2a0d1d7d0edb746a22e"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.15.0/fir-linux-amd64"
      sha256 "44ba77bb3d343933ea98ce797738336022c8121cb11efa3d6be5b01fc3096a29"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.15.0/fir-linux-armv6"
      sha256 "ee2558dc40784c5312679a4c79caba257e531e4601b83b0f09ff223300dd3da8"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.15.0/fir-linux-arm64"
      sha256 "12fa4c78673dbc320560ea8c379afb23f1e0edf5cc4c38c531e97bc20e260ca1"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.15). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.15

      To go back to the rolling latest:
        brew unlink fir@1.15
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
