# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT12 < Formula
  desc "Fast, portable AI coding agent (pinned 1.2)"
  homepage "https://github.com/kfet/fir"
  version "1.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.2.2/fir-darwin-amd64"
      sha256 "2de09e27edf5698f2f85d9fcb53af7a3befcc99f11ba167489b21b6ad0c28caf"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.2.2/fir-darwin-arm64"
      sha256 "c2443ea7257dba6433c6ff806a0bc1608eaecae5e529e7f8519b8ef453330662"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.2.2/fir-linux-amd64"
      sha256 "2e156d6e6d0383d16946fdd7e66a9009a4c0dd3e5e22b15569c64685a0cc3f20"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.2.2/fir-linux-armv6"
      sha256 "0fd6f714943ad3dcb34309eaf10b3e8528ee63c948a3c535240d5be523602e80"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.2.2/fir-linux-arm64"
      sha256 "91b3b1c7452ef96207160a0e5c65f6714914f649722faf7fd9db374c086f4df4"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.2). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.2

      To go back to the rolling latest:
        brew unlink fir@1.2
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
