# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT077 < Formula
  desc "Fast, portable AI coding agent (pinned 0.77)"
  homepage "https://github.com/kfet/fir"
  version "0.77.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.77.0/fir-darwin-amd64"
      sha256 "075da1f817b965a0a6a88b915fd41f84d879061b75dc14036b9131f316851f17"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.77.0/fir-darwin-arm64"
      sha256 "5293524eadae9bfd897d7432ca3fc781d0afff682981f87137637520416070f0"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.77.0/fir-linux-amd64"
      sha256 "5bc28b20119a78e5dad14b282b0ebd24e7c9369aeba41008801b740921f439de"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.77.0/fir-linux-armv6"
      sha256 "1c7edaae50496137a091d8d7cc40606c33b2aec78ec956afe94e9b8a3ec34949"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.77.0/fir-linux-arm64"
      sha256 "e042ab796fab243f1fd43343b8214be03f78dea387635a95c2dfc4e627d81579"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.77). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.77

      To go back to the rolling latest:
        brew unlink fir@0.77
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
