# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT090 < Formula
  desc "Fast, portable AI coding agent (pinned 0.90)"
  homepage "https://github.com/kfet/fir"
  version "0.90.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.90.0/fir-darwin-amd64"
      sha256 "985cd87e3f0cb0db118022293f7dda98e472723e94a4cde732f2b0bb0a912631"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.90.0/fir-darwin-arm64"
      sha256 "e39a74383c3d266b2f8df54d9b0528b5c38f71ebe42ff8e6e71630c6d3bb2ed0"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.90.0/fir-linux-amd64"
      sha256 "15b60239571cf5b471b3e3a6619d034a6ea6c45a4dbb8703d01d758c82579aac"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.90.0/fir-linux-armv6"
      sha256 "aaef3452a7d50e2931e170ba64b0172f40bbb791958524f436c59ebb31b4ba3a"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.90.0/fir-linux-arm64"
      sha256 "5f30cf1520680176caad118a8fb5cc345b686c49cbe89daa38659871a4b55746"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.90). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.90

      To go back to the rolling latest:
        brew unlink fir@0.90
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
