# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT15 < Formula
  desc "Fast, portable AI coding agent (pinned 1.5)"
  homepage "https://github.com/kfet/fir"
  version "1.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v1.5.0/fir-darwin-amd64"
      sha256 "70c16b988a90d31230257f584f5e294c10ca2d47eef7e686c36d95c5b8d05796"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v1.5.0/fir-darwin-arm64"
      sha256 "f965bd3ddf04a874182ad830410478cde233f546df9c5c30af7339f1ec588348"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.5.0/fir-linux-amd64"
      sha256 "68987bc16449517fef3b7847a3ff1ee54b7c0caa7d8640358f7df7f098bde8e0"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.5.0/fir-linux-armv6"
      sha256 "968fc791dab748702d7890841c44abd475755d598aed82a5f5354aa24927e927"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v1.5.0/fir-linux-arm64"
      sha256 "0fae6fd8322597c7a55606e42207c0f65703843e574ee22fc30817d54993c2c9"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@1.5). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@1.5

      To go back to the rolling latest:
        brew unlink fir@1.5
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
