# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT081 < Formula
  desc "Fast, portable AI coding agent (pinned 0.81)"
  homepage "https://github.com/kfet/fir"
  version "0.81.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.81.0/fir-darwin-amd64"
      sha256 "18e55a55a814393fb7ed8e6eb3449c65e934c11ea91ce5a59ab3315ca596b763"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.81.0/fir-darwin-arm64"
      sha256 "1a8e834da8528e196a8f788ea9c253765d17672334a062570112593fdee1ac0c"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.81.0/fir-linux-amd64"
      sha256 "5fc4a5302fe2fc9a4e5683ebc0828448b42bddf5a71ad31a5dcc3e278b2b5141"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.81.0/fir-linux-armv6"
      sha256 "a1cafb98aaf0a5f44258ea2e285699d6e44d6c651407fd9a0394624fb4997f65"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.81.0/fir-linux-arm64"
      sha256 "0dc159d18f3c38041b80babbeb557f18fd665f0ed2b64fc959a15010f1b44a5d"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.81). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.81

      To go back to the rolling latest:
        brew unlink fir@0.81
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
