# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT074 < Formula
  desc "Fast, portable AI coding agent (pinned 0.74)"
  homepage "https://github.com/kfet/fir"
  version "0.74.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.74.2/fir-darwin-amd64"
      sha256 "aab65a0bebd586febeb55e07107d7129b983474e6cf690d9d611285a66fd71a8"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.74.2/fir-darwin-arm64"
      sha256 "bd8b3988e3f52233e529d2cff54a10513602a1a496b0de30a82e9603f7a14f7d"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.74.2/fir-linux-amd64"
      sha256 "649d3f37393fdc156f97e0f68d202ca3e494c1f9cd36cb901aa9985caf057806"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.74.2/fir-linux-armv6"
      sha256 "a5cdd36c8579a03b208e9a9014f4859922d1bdfe61ae1e57475eded86e4bc1f5"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.74.2/fir-linux-arm64"
      sha256 "492246f75a7f0209c426eb5f5ee2a21c9784a920f622b48d8d2f4f91e6d06caf"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.74). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.74

      To go back to the rolling latest:
        brew unlink fir@0.74
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
