# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT098 < Formula
  desc "Fast, portable AI coding agent (pinned 0.98)"
  homepage "https://github.com/kfet/fir"
  version "0.98.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.98.2/fir-darwin-amd64"
      sha256 "244b6cc29397a382edea82783d3310cc04f7d25eec8bcbb9106f2255b5c53c26"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.98.2/fir-darwin-arm64"
      sha256 "90d051b8973817b0a124e9dd3a504003a58fa49efb1c4c87c7dd0d98c9806681"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.98.2/fir-linux-amd64"
      sha256 "5089f7adeadf5d34c73b52ba7caac526ed2fd080a55909af522d69d4045f9074"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.98.2/fir-linux-armv6"
      sha256 "77153c80f569bf551768877c1a5b3cf48fbf5d4a6d7a50816e66bae6ce74877a"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.98.2/fir-linux-arm64"
      sha256 "206a32051b98d5a08783006e353b68475f32de5d772b6e2e7efc93d4d942a0dc"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.98). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.98

      To go back to the rolling latest:
        brew unlink fir@0.98
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
