# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PoeAcp < Formula
  desc "HTTP relay between Poe server bots and ACP-speaking agents"
  homepage "https://github.com/kfet/poe-acp"
  version "0.72.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/poe-acp/releases/download/v0.72.0/poe-acp-darwin-amd64"
      sha256 "6fa4be0ed161d800f849407bd1e1fdaf33eea90eda29465ae113550f31b3c6aa"

      define_method(:install) do
        bin.install Dir["poe-acp-*"].first => "poe-acp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/poe-acp/releases/download/v0.72.0/poe-acp-darwin-arm64"
      sha256 "9253bab9e6cde88897779e0196b5add01201b5f054e16eeffc43faa7a7e35ed6"

      define_method(:install) do
        bin.install Dir["poe-acp-*"].first => "poe-acp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/poe-acp/releases/download/v0.72.0/poe-acp-linux-amd64"
      sha256 "5a936dbdaa2f6dd1a21e2724a8748bbff3b650476dd5346c538241428e91e78c"
      define_method(:install) do
        bin.install Dir["poe-acp-*"].first => "poe-acp"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/poe-acp/releases/download/v0.72.0/poe-acp-linux-armv6"
      sha256 "e0600458201a95eeeebc24c59d2977fa8f61efe445cea7025c9f835a6130ee77"
      define_method(:install) do
        bin.install Dir["poe-acp-*"].first => "poe-acp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/poe-acp/releases/download/v0.72.0/poe-acp-linux-arm64"
      sha256 "ec2efc1d531d87c2930aa3affd1ff150dc642095521ebff7de80009d174b013c"
      define_method(:install) do
        bin.install Dir["poe-acp-*"].first => "poe-acp"
      end
    end
  end

  test do
    system "#{bin}/poe-acp", "--version"
  end
end
