# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PoeAcp < Formula
  desc "HTTP relay between Poe server bots and ACP-speaking agents"
  homepage "https://github.com/kfet/poe-acp"
  version "0.79.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/poe-acp/releases/download/v0.79.0/poe-acp-darwin-amd64"
      sha256 "8087cc842ea67556642400ca068d0fe9bc92e77a9eb40809da178b9a35dc1e28"

      define_method(:install) do
        bin.install Dir["poe-acp-*"].first => "poe-acp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/poe-acp/releases/download/v0.79.0/poe-acp-darwin-arm64"
      sha256 "c6df085b0299c969b42e0bd6cbae2d1280a2b2badca9fef927aa392060752d33"

      define_method(:install) do
        bin.install Dir["poe-acp-*"].first => "poe-acp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/poe-acp/releases/download/v0.79.0/poe-acp-linux-amd64"
      sha256 "d9ab7fc724c88d59a2e9c91174abf2371fec7c4fd8a61449a2398d2bf32d4ac0"
      define_method(:install) do
        bin.install Dir["poe-acp-*"].first => "poe-acp"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/poe-acp/releases/download/v0.79.0/poe-acp-linux-armv6"
      sha256 "fc17f2ff2037473bb0174959c9b9b8ae17867a86447a962c5e63244c77c2b276"
      define_method(:install) do
        bin.install Dir["poe-acp-*"].first => "poe-acp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/poe-acp/releases/download/v0.79.0/poe-acp-linux-arm64"
      sha256 "e2047149f53925967bb9df59907e4dbc081c1c7ffd533feaf005cec9ee16ec31"
      define_method(:install) do
        bin.install Dir["poe-acp-*"].first => "poe-acp"
      end
    end
  end

  test do
    system "#{bin}/poe-acp", "--version"
  end
end
