# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PoeAcp < Formula
  desc "HTTP relay between Poe server bots and ACP-speaking agents"
  homepage "https://github.com/kfet/poe-acp"
  version "0.67.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/poe-acp/releases/download/v0.67.0/poe-acp-darwin-amd64"
      sha256 "c818441e290d6d6c927e448417e454b77ec5e3aef9d05192cc4328bc3cd2c918"

      define_method(:install) do
        bin.install Dir["poe-acp-*"].first => "poe-acp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/poe-acp/releases/download/v0.67.0/poe-acp-darwin-arm64"
      sha256 "da78038a470cf351376bd5fea8430a8b51ca307e337c4bc269ba563d67b0f79f"

      define_method(:install) do
        bin.install Dir["poe-acp-*"].first => "poe-acp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/poe-acp/releases/download/v0.67.0/poe-acp-linux-amd64"
      sha256 "085af3ba585597fb70381b5f4c3f848cc6aa67131852e6d2bbf449759534482d"
      define_method(:install) do
        bin.install Dir["poe-acp-*"].first => "poe-acp"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/poe-acp/releases/download/v0.67.0/poe-acp-linux-armv6"
      sha256 "fe827caa3544940e45a8c1c879d155cbd5ea69d69e79089f3c5ea04d0c89cd3d"
      define_method(:install) do
        bin.install Dir["poe-acp-*"].first => "poe-acp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/poe-acp/releases/download/v0.67.0/poe-acp-linux-arm64"
      sha256 "963155333a2ffb0e6e0ec42a420c9ac7e9d04d8eae4d9708d2250247a06336c6"
      define_method(:install) do
        bin.install Dir["poe-acp-*"].first => "poe-acp"
      end
    end
  end

  test do
    system "#{bin}/poe-acp", "--version"
  end
end
