# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackAcp < Formula
  desc "Slack bot that relays each thread to a spawned ACP-speaking agent"
  homepage "https://github.com/kfet/slack-acp"
  version "0.10.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/slack-acp/releases/download/v0.10.1/slack-acp-darwin-amd64"
      sha256 "fdb92786f622ecb27d3e6b359e531065a6ca8b5705ddb1c2aba69c46b3ae98c5"

      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/slack-acp/releases/download/v0.10.1/slack-acp-darwin-arm64"
      sha256 "2ae14dc746620b9bb5b5c7a64d32aac77f9dc2d16d9b45281af53a7cab0948e7"

      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/slack-acp/releases/download/v0.10.1/slack-acp-linux-amd64"
      sha256 "1718205eda49910330ebd514c2f43265815ddd024019b7b998cc1866e3c3b8fe"
      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/slack-acp/releases/download/v0.10.1/slack-acp-linux-armv6"
      sha256 "fcaeac2c6925d89ee99bd53424f265f8ea7026d003361abda807f09b0dd9fa02"
      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/slack-acp/releases/download/v0.10.1/slack-acp-linux-arm64"
      sha256 "f99710728af9130ea56a12653db03e6db7a40ed1f3227c841896ec6c098f00eb"
      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
  end

  test do
    system "#{bin}/slack-acp", "--version"
  end
end
