# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackAcp < Formula
  desc "Slack bot that relays each thread to a spawned ACP-speaking agent"
  homepage "https://github.com/kfet/slack-acp"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/slack-acp/releases/download/v0.5.0/slack-acp-darwin-amd64"
      sha256 "0d82821838019356b1800277be98ba123932878819c483eabf44e648ac2fcf30"

      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/slack-acp/releases/download/v0.5.0/slack-acp-darwin-arm64"
      sha256 "d95ec567306f5ef7d4ff5ecbea222d693c00ec637a721f0fbddc1def2ac33236"

      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/slack-acp/releases/download/v0.5.0/slack-acp-linux-amd64"
      sha256 "04ca3acafd1eff1a83c5bbe75a92f46f598df5efe4921b6d2cbdc0dc1f5b84d9"
      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/slack-acp/releases/download/v0.5.0/slack-acp-linux-armv6"
      sha256 "c4ecad2905774310e3e646a406b386e6ae1058931e01c736ac4e42cb1d196c37"
      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/slack-acp/releases/download/v0.5.0/slack-acp-linux-arm64"
      sha256 "d1eb84d12c80b8f866a3552ca85e0b0349aef67b5f58378001e22f982f6f2355"
      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
  end

  test do
    system "#{bin}/slack-acp", "--version"
  end
end
