# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackAcp < Formula
  desc "Slack bot that relays each thread to a spawned ACP-speaking agent"
  homepage "https://github.com/kfet/slack-acp"
  version "0.11.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/slack-acp/releases/download/v0.11.1/slack-acp-darwin-amd64"
      sha256 "1025af664281efb972afd1713a0ed40f740137cc89c0e2bcaa1e641c283f35f5"

      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/slack-acp/releases/download/v0.11.1/slack-acp-darwin-arm64"
      sha256 "83ca3518432545de4e8466ff46d8866b9f6f402a35d8046e0e3cff76508fab9c"

      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/slack-acp/releases/download/v0.11.1/slack-acp-linux-amd64"
      sha256 "4670ac6ecf2d807c5d7ba48f6f73b3bc5b7e3a2786c15628f44d9f903042504a"
      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/slack-acp/releases/download/v0.11.1/slack-acp-linux-armv6"
      sha256 "f94b1a7ceb4b2c3eb9f9004b245998f662e3c5315a19fee8b852bf955b7216d3"
      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/slack-acp/releases/download/v0.11.1/slack-acp-linux-arm64"
      sha256 "a7dfebeca4a60227605194c4e9cc671358dc9edc41d0dbd4c7021a7f15ce4dcd"
      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
  end

  test do
    system "#{bin}/slack-acp", "--version"
  end
end
